#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_SETTINGS                            101
#define IDB_GOOGLEBTN                           106
#define IDB_GOOGLEFONT                          107
#define IDC_VERSION                             108
#define IDB_ICON                                110
#define IDD_ADDURL                              112
#define IDR_CONNECTRES1                         113
#define IDD_EXCLUSIONS                          116
#define IDC_CONNECTBTN                          1001
#define IDC_AVATAR                              1005
#define IDC_USERNAME                            1006
#define IDC_YouTubeURL                          1007
#define IDC_YouTubeURLCAPTION                   1008
#define IDC_PLAYLISTTITLE                       1009
#define IDC_PLAYLISTTITLECAPTION                1010
#define IDC_CREATENEW                           1011
#define IDC_LISTVIEW                            1012
#define IDC_MAINFRAME                           40000
#define IDC_AUTHGROUPBOX                        40001
#define IDC_USERINFO                            40002
#define IDC_YTDLPARAMSTEXT                      40003
#define IDC_YTDLFORCE                           40004
#define IDC_CHECKONSTARTUP                      40005
#define IDC_MONITORGROUPBOX                     40006
#define IDC_CHECKEVERY                          40007
#define IDC_HOURS                               40008
#define IDC_CHECKEVERYVALUE                     40009
#define IDC_CHECKEVERYVALUESPIN                 40010
#define IDC_YTDLPARAMS                          40011
#define IDC_SECONDS                             40012
#define IDC_YTDLTIMEOUT                         40013
#define IDC_YTDLTIMEOUTSPIN                     40014
#define IDC_YTDLTIMEOUTTEXT                     40015
#define IDC_MONITORPLAYLISTS                    40016
#define IDC_YTDLUPDATE                          40017
#define IDC_EXCLUSIONSGROUPBOX                  40018
#define IDC_YTAPIGROUPBOX                       40018
#define IDC_MANAGEEXCLUSIONS                    40019
#define IDC_YTDLGROUPBOX                        40020
#define IDC_YTAPIKEYTEXT                        40021
#define IDC_YTAPIKEY                            40022
#define IDC_YTAPIKEYUSAGE                       40023
#define IDC_LOGGROUPBOX                         40024
#define IDC_DONTSHOWERRORS                      40025
#define IDC_VIEWLOGS                            40026
